[project]
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "tissue-biomarker-pipeline"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

dag = "snakemake -F --dag | dot -Tsvg > resources/dag.svg"
rulegraph = "snakemake -F --rulegraph | dot -Tsvg > resources/rulegraph.svg"
filegraph = "snakemake -F --filegraph | dot -Tsvg > resources/filegraph.svg"
graphs = { depends-on = [
  "dag",
  "rulegraph",
  "filegraph",
], description = "Generate all the graphs" }

snake = "snakemake  --printshellcmds --show-failed-logs --rerun-incomplete"
clean = "rm -rf procdata logs .snakemake" # rawdata download is expensive..


[dependencies]
r-base = ">=4.4.1,<5"
r-essentials = ">=4.4,<5"
"r-data.table" = ">=1.15.4,<2"
r-pak = ">=0.8.0,<0.9"
radian = ">=0.6.13,<0.7"
snakemake = ">=8.20.5,<9"
r-deps = ">=0.4.0,<0.5"
graphviz = ">=12.0.0,<13"

[pypi-dependencies]
orcestra-downloader = ">=0.11.0, <0.12"

